/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemoveBackgroundRouteImport } from './routes/remove-background'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as MergeSplitPdfRouteImport } from './routes/merge-split-pdf'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as ConvertImageRouteImport } from './routes/convert-image'
import { Route as CompressImageRouteImport } from './routes/compress-image'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RemoveBackgroundRoute = RemoveBackgroundRouteImport.update({
  id: '/remove-background',
  path: '/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeSplitPdfRoute = MergeSplitPdfRouteImport.update({
  id: '/merge-split-pdf',
  path: '/merge-split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertImageRoute = ConvertImageRouteImport.update({
  id: '/convert-image',
  path: '/convert-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImageRoute = CompressImageRouteImport.update({
  id: '/compress-image',
  path: '/compress-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-split-pdf': typeof MergeSplitPdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pricing': typeof PricingRoute
  '/remove-background': typeof RemoveBackgroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-split-pdf': typeof MergeSplitPdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pricing': typeof PricingRoute
  '/remove-background': typeof RemoveBackgroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/merge-split-pdf': typeof MergeSplitPdfRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/pricing': typeof PricingRoute
  '/remove-background': typeof RemoveBackgroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compress-image'
    | '/convert-image'
    | '/image-to-pdf'
    | '/merge-split-pdf'
    | '/pdf-to-image'
    | '/pricing'
    | '/remove-background'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compress-image'
    | '/convert-image'
    | '/image-to-pdf'
    | '/merge-split-pdf'
    | '/pdf-to-image'
    | '/pricing'
    | '/remove-background'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compress-image'
    | '/convert-image'
    | '/image-to-pdf'
    | '/merge-split-pdf'
    | '/pdf-to-image'
    | '/pricing'
    | '/remove-background'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompressImageRoute: typeof CompressImageRoute
  ConvertImageRoute: typeof ConvertImageRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  MergeSplitPdfRoute: typeof MergeSplitPdfRoute
  PdfToImageRoute: typeof PdfToImageRoute
  PricingRoute: typeof PricingRoute
  RemoveBackgroundRoute: typeof RemoveBackgroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remove-background': {
      id: '/remove-background'
      path: '/remove-background'
      fullPath: '/remove-background'
      preLoaderRoute: typeof RemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-split-pdf': {
      id: '/merge-split-pdf'
      path: '/merge-split-pdf'
      fullPath: '/merge-split-pdf'
      preLoaderRoute: typeof MergeSplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert-image': {
      id: '/convert-image'
      path: '/convert-image'
      fullPath: '/convert-image'
      preLoaderRoute: typeof ConvertImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-image': {
      id: '/compress-image'
      path: '/compress-image'
      fullPath: '/compress-image'
      preLoaderRoute: typeof CompressImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompressImageRoute: CompressImageRoute,
  ConvertImageRoute: ConvertImageRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  MergeSplitPdfRoute: MergeSplitPdfRoute,
  PdfToImageRoute: PdfToImageRoute,
  PricingRoute: PricingRoute,
  RemoveBackgroundRoute: RemoveBackgroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
