/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConvertImageRouteImport } from './routes/convert-image'
import { Route as CompressImageRouteImport } from './routes/compress-image'
import { Route as IndexRouteImport } from './routes/index'

const ConvertImageRoute = ConvertImageRouteImport.update({
  id: '/convert-image',
  path: '/convert-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImageRoute = CompressImageRouteImport.update({
  id: '/compress-image',
  path: '/compress-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress-image': typeof CompressImageRoute
  '/convert-image': typeof ConvertImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compress-image' | '/convert-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compress-image' | '/convert-image'
  id: '__root__' | '/' | '/compress-image' | '/convert-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressImageRoute: typeof CompressImageRoute
  ConvertImageRoute: typeof ConvertImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/convert-image': {
      id: '/convert-image'
      path: '/convert-image'
      fullPath: '/convert-image'
      preLoaderRoute: typeof ConvertImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-image': {
      id: '/compress-image'
      path: '/compress-image'
      fullPath: '/compress-image'
      preLoaderRoute: typeof CompressImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressImageRoute: CompressImageRoute,
  ConvertImageRoute: ConvertImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
